# Generated by Django 4.0.5 on 2022-12-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cliente_is_top1_cliente_is_top2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='is_top1',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_top2',
        ),
    ]
