# Generated by Django 4.0.5 on 2022-12-29 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cliente_is_top1_remove_cliente_is_top2'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente_id',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
