# Generated by Django 4.0.5 on 2022-12-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_venda_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='produto_quantidade',
        ),
    ]
