# Generated by Django 4.0.5 on 2022-12-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_desconto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
