# Generated by Django 4.0.5 on 2022-12-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_produto_produto_desconto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='ProdutoPedido',
        ),
    ]
