# Generated by Django 4.0.5 on 2022-12-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_pedido_produtopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(to='main.produtopedido'),
        ),
    ]
