# Generated by Django 4.0.5 on 2022-12-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_venda_cliente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id',
            new_name='pedido_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pedido',
        ),
    ]
