# Generated by Django 4.0.5 on 2022-12-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_id_pedido_pedido_id_remove_pedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
    ]
