# Generated by Django 4.0.5 on 2022-12-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_venda_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_img',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
