# Generated by Django 4.0.5 on 2022-12-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_produto_produto_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='produto_img',
            new_name='produto_slug',
        ),
    ]
