# Generated by Django 4.0.5 on 2023-01-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_items',
        ),
    ]
