# Generated by Django 4.0.5 on 2023-01-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_cartitem_total_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_timestamp',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_updated',
        ),
    ]
