# Generated by Django 4.0.5 on 2023-01-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_cartitems_rename_cart_id_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
