# Generated by Django 4.0.5 on 2023-01-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered_products',
            field=models.ManyToManyField(to='main.product'),
        ),
    ]
