# Generated by Django 4.0.5 on 2023-01-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_cart_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
    ]
