# Generated by Django 4.0.5 on 2023-01-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_cart_fee_remove_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
