# Generated by Django 4.0.5 on 2023-01-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='order_status',
            field=models.CharField(choices=[('1', 'Aguardando pagamento'), ('2', 'Mercadoria à caminho'), ('3', 'Entregue')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('B', 'Boleto'), ('P', 'PIX')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
