# Generated by Django 4.0.5 on 2023-01-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_cart_address_cart_order_status_cart_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_method',
        ),
    ]
