# Generated by Django 4.0.5 on 2023-01-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_cart_address_remove_cart_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
