# Generated by Django 4.0.5 on 2023-01-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cartitems'),
            preserve_default=False,
        ),
    ]
