# Generated by Django 4.0.5 on 2023-01-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_cartitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
