# Generated by Django 4.0.5 on 2023-01-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_order_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
