# Generated by Django 4.0.5 on 2023-01-11 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_remove_order_cart_items_order_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cartitems'),
            preserve_default=False,
        ),
    ]
