# Generated by Django 4.0.5 on 2023-01-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_remove_order_cart_items_order_cart_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
