# Generated by Django 4.0.5 on 2023-01-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_address_cart_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='shipping_address',
            new_name='address',
        ),
    ]
